### PR TITLE
Copyright notice updated

### PR DESCRIPTION
**Pull request by VishakhaSainani**
fixes: #80 

I have updated the the Copyright line. Check it out.

### CODE REVIEW

**Comment by VishakhaSainani** [comment]
@nxglabs Please review the change.

**Comment by nxglabs** [comment]
Please share the screenshots

**Comment by VishakhaSainani** [comment]
@nxglabs I am unable to login on my local machine. So I cannot view the changes. But I think since it's a normal change, it must have been implemented correctly.

**Comment by nxglabs** [comment]
I wont be able to merge a UI change without screenshots.

**Comment by VishakhaSainani** [comment]
@nxglabs I did setup the frontend. Can you tell me the steps to setup the backend so that I can Login and check.

**Comment by nxglabs** [comment]
Read the updated INSTALLATION.md
It has instructions for running the frontend locally without installing the backend.

**Comment by VishakhaSainani** [comment]
But I still can't login by just running the frontend . 
Here the error,
contracts - Signup page - Google Chrome 31-10-2023 00_16_46

And even if I try running backend. It's giving some other error in index.js.
@nxglabs Can you check?

**Comment by nxglabs** [comment]
Share screenshot of your .env

**Comment by VishakhaSainani** [comment]
abc

**Comment by nxglabs** [comment]
Clear the data of your browser or try opening it in Incognito window

**Comment by andrew-opensignlabs** [comment]
@all-contributors add @VishakhaSainani for code

**Pull request merged**
