### PR TITLE
Specify signatureVersion for AWS S3

### LINKED ISSUE #1138: [Bug]: "Failed to load PDF file."
### Issue Description

At "Request signature", trying to place signature on to PDF, the thumbnail does not load and throws error: `Failed to load PDF file.`

Docker STDOUT:
```
OpenSign-container        |  HTTP  8/31/2024 11:39:35 AM 172.18.0.3 GET /placeHolderSign/T6YAU4fWg5
OpenSign-container        |  HTTP  8/31/2024 11:39:35 AM 172.18.0.3 Returned 200 in 2 ms
OpenSign-container        |  HTTP  8/31/2024 11:39:35 AM 172.18.0.3 GET /manifest.json
OpenSign-container        |  HTTP  8/31/2024 11:39:35 AM 172.18.0.3 Returned 200 in 1 ms
OpenSign-container        |  HTTP  8/31/2024 11:39:35 AM 172.18.0.3 GET /locales/en-GB/translation.json
OpenSign-container        |  HTTP  8/31/2024 11:39:35 AM 172.18.0.3 Returned 200 in 1 ms
OpenSign-container        |  HTTP  8/31/2024 11:39:35 AM 172.18.0.3 GET /locales/en/translation.json
OpenSign-container        |  HTTP  8/31/2024 11:39:35 AM 172.18.0.3 Returned 200 in 3 ms
OpenSign-container        |  HTTP  8/31/2024 11:39:35 AM 172.18.0.3 GET /version.txt
OpenSign-container        |  HTTP  8/31/2024 11:39:35 AM 172.18.0.3 Returned 304 in 5 ms
mongo-container           | {"t":{"$date":"2024-08-31T11:39:32.482+00:00"},"s":"I",  "c":"WTCHKPT",  "id":22430,   "ctx":"Checkpointer","msg":"WiredTiger message","attr":{"message":{"ts_sec":1725104372,"ts_usec":482041,"thread":"1:0x7621b3200640","session_name":"WT_SESSION.checkpoint","category":"WT_VERB_CHECKPOINT_PROGRESS","category_id":6,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"saving checkpoint snapshot min: 330, snapshot max: 330 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 1"}}}
```

### Expected Behavior

It should load the thumbnail of the pdf and its pages.

### Current Behavior

Error: `Failed to load PDF file.`

### Steps to reproduce

1. Create Digital Ocean droplet
2. Point subdomain A record to the IP address of the droplet
3. Run without changing anything `export HOST_URL=https://sign.FQDN.io && curl --remote-name-all https://raw.githubusercontent.com/OpenSignLabs/OpenSign/docker_beta/docker-compose.yml https://raw.githubusercontent.com/OpenSignLabs/OpenSign/docker_beta/Caddyfile https://raw.githubusercontent.com/OpenSignLabs/OpenSign/docker_beta/.env.local_dev && mv .env.local_dev .env.prod && docker compose up --force-recreate`
4. Create admin account
5. Create first `Request signatures`
6. On the last step of `Request signatures`, the PDF does not load

### Screenshots of the issue(optional)

Screenshot 2024-08-31 at 13 47 12

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

Ubuntu 24.04

### What browsers are you seeing the problem on?

Safari

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

Latest [version: v2.2.0]

### What environment are you seeing the problem on?

Production (app.opensignlabs.com)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### PR DESCRIPTION
**Pull request by hanicker**
Hi, to me these changes seems to fix #1138

### CODE REVIEW

**Comment by andrew-opensignlabs** [comment]
Looks good to me.
@pravinOpenSign can you please test this?

**Review by prafull-opensignlabs — APPROVED** [review]

**Comment by EDIflyer** [comment]
Has this been merged into the main release yet or is it still pending? I tried a new London AWS S3 bucket and still getting the same error.

**Comment by andrew-opensignlabs** [comment]
I guess its not available on main yet. Should be available in this week's release.

**Comment by EDIflyer** [comment]
OK, thanks @andrew-opensignlabs - I'll leave my S3 bucket as it is for London and check back after the new release - fingers crossed!

**Pull request merged**
