### PR TITLE
#169 - Fix Footer overlaps on signature toolbar in mobile view

### PR DESCRIPTION
**Pull request by rishabjasrotia**
#169 - Fix Footer overlaps on signature toolbar in mobile view

### CODE REVIEW

**Comment by rishabjasrotia** [comment]
Hello @andrew-opensignlabs @nxglabs 
Please find the quick fix for issue #169 

cc @raktima-opensignlabs

**Comment by rishabjasrotia** [comment]
Hello @nxglabs ,
I have added fix for #168
Please review PR.

**Comment by nxglabs** [comment]
@rishabjasrotia We need to have the signature footer sticking to the bottom of the screen in mobile view. It's because when we release the mobile app it will be a better user experience. We are planning to launch the v1 mobile apps as embedded webviews of current react app.

**Comment by rishabjasrotia** [comment]
Okay I will modify it to make it stick to footer.
While how we need to handle then the footer copyright?

In mobile View it should not be visible?
@nxglabs

**Pull request closed without merging**
