### PR TITLE
Create translation.json for DE

### PR DESCRIPTION
**Pull request by astrakid**
just started translation, 3% completed. rest will follow.

### CODE REVIEW

**Comment by Zathiel** [comment]
Hello @astrakid 

Thanks for this DE translation

Can you please put this PR in draft according of you have said this is not ready yet

Regards

**Comment by astrakid** [comment]
sorry, how can i set it to draft?

**Comment by Zathiel** [comment]
you should have a little button on the bottom of the chat or in the bottom right to send to draft

**Comment by astrakid** [comment]
yeah, found it "convwert to draft". thx.

**Pull request closed without merging**
