### PR TITLE
Solved Issue67

### PR DESCRIPTION
**Pull request by Monilprajapati**
Done with Issue #67.
Hacktoberfest 2023

### CODE REVIEW

**Comment by Monilprajapati** [comment]
@andrew-opensignlabs  Please check this, add hacktoberfest label and merge it asap

**Comment by Monilprajapati** [comment]
Please also add the Hacktoberfest Label @nxglabs

**Comment by nxglabs** [comment]
Its already added to the associated issue. That should be enough but i am adding it again here for you.

**Comment by Monilprajapati** [comment]
> Its already added to the associated issue. That should be enough but i am adding it again here for you.

Yeah but they are only considering the PR which has this Hacktoberfest Label to count it in valid PR that's why!!

**Pull request merged**
